version: "3.9"

services:
  wiki_searcher:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: wiki_searcher
    ports:
      - "3000:3000"

    command: "pipenv run wiki_searcher"