name: Wikipedia Searcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        python -m pipenv install --dev
    - name: Lint with flake8
      run: |
        python -m pipenv run lint_syntax
        python -m pipenv run lint_warnings
    - name: Test with pytest and get coverage
      run: |
        export COVERAGE_FILE="./.github/coverage/.coverage"
        python -m pipenv run tests_with_coverage
        cd .github/coverage && python -m pipenv run coverage-badge -o ./.github/coverage/coverage.svg
